"""add fraud alert explanation and expected loss

Persists *why* an alert was raised alongside *how much* is at stake.

- `explanation` (JSONB): the rules that fired, with the real values behind
  them, plus the scoring model name/version. Stored on the alert rather than
  recomputed on read so an alert stays explainable after the model version
  that produced it is retired.
- `expected_loss` (NUMERIC(15,2)): fraud_probability x amount. Triage queues
  order by this rather than by probability, so a 40% alert on N$50,000
  outranks a 95% alert on N$500.

Hand-written rather than autogenerated: `alembic revision --autogenerate`
also picked up pre-existing index/constraint drift between the models and
the deployed schema, which is unrelated to this change and would have been
applied silently. Only the two columns below belong in this revision.

Revision ID: 50599d6c5d6a
Revises: e45a65c684d5
Create Date: 2026-07-27 23:23:27.821576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '50599d6c5d6a'
down_revision: Union[str, None] = 'e45a65c684d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "fraud_alerts",
        sa.Column(
            "explanation",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text("'{}'::jsonb"),
        ),
    )
    op.add_column(
        "fraud_alerts",
        sa.Column("expected_loss", sa.Numeric(15, 2), nullable=True),
    )

    # Backfill exposure for alerts raised before this column existed, so the
    # triage ordering is correct on day one rather than treating history as
    # zero-exposure. `explanation` stays '{}' for these: the reasons were
    # never captured and must not be invented after the fact.
    op.execute(
        "UPDATE fraud_alerts "
        "SET expected_loss = ROUND(fraud_probability * amount, 2) "
        "WHERE expected_loss IS NULL"
    )

    # The server_default exists only to make the NOT NULL add safe against
    # existing rows; the application always supplies the value explicitly.
    op.alter_column("fraud_alerts", "explanation", server_default=None)


def downgrade() -> None:
    op.drop_column("fraud_alerts", "expected_loss")
    op.drop_column("fraud_alerts", "explanation")
